---
# ----------------
# General
# ----------------
# Base home assistant configuration
# used to bootstrap remaining configs.

homeassistant:
  currency: USD
  elevation: !env_var HASS_ELEVATION
  name: Home
  latitude: !env_var HASS_LATITUDE
  longitude: !env_var HASS_LONGITUDE
  unit_system: imperial
  time_zone: America/Los_Angeles

  external_url: !env_var HASS_URL
  internal_url: !env_var HASS_URL

  packages: !include_dir_named packages

# ----------------
# General http
# ----------------
# HTTP settings to handle serving files for frontend
# https://www.home-assistant.io/integrations/http/
http:
  server_host: 0.0.0.0
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - !env_var HASS_TRUSTED_PROXIES_1
    - !env_var HASS_TRUSTED_PROXIES_1

# -----------------
# Core integrations
# -----------------
# Manually import core integrations
# https://www.home-assistant.io/integrations/default_config/
automation manual: !include_dir_merge_list automations
automation ui: !include automations.yaml
cloud:
config:
dhcp:
frontend:
  themes: !include_dir_named themes/
history:
image:
map:
media_source:
mobile_app:
my:
logbook:
person:
shell_command: !include_dir_merge_named shell_commands
sun:
system_health:
tag:
updater:
zone:
