---
name: Deploy config changes

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: joelwmale/webhook-action@87f230c372975905ed19749b38b1ba6698c840c3
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{}'
